SELECT * FROM (
select COUNT(*) AS TOTAL_COUNT
from {{ref('DBT_CUS_CUSTOMER')}}
WHERE EDW_LOAD_TIMESTAMP >= (SELECT MAX(EDW_LOAD_TIMESTAMP) FROM {{ref('STG_CUS_CUSTOMER')}}))
WHERE TOTAL_COUNT = 0